// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AssetList: typeof import('./src/components/AssetList/index.vue')['default']
    AttributeEditor: typeof import('./src/components/SettingConfig/AttributeEditor/index.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor/index.vue')['default']
    CodeEditorModal: typeof import('./src/components/SettingConfig/components/CodeEditorModal.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EventCodeEditor: typeof import('./src/components/SettingConfig/components/EventCodeEditor.vue')['default']
    EventEditor: typeof import('./src/components/SettingConfig/EventEditor/index.vue')['default']
    Form: typeof import('./src/components/SettingConfig/components/Form.vue')['default']
    FormItem: typeof import('./src/components/SettingConfig/components/FormItem.vue')['default']
    PreviewModal: typeof import('./src/components/PreviewModal/index.vue')['default']
    Render: typeof import('./src/components/Render/index.vue')['default']
    RenderItem: typeof import('./src/components/Render/RenderItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingConfig: typeof import('./src/components/SettingConfig/index.vue')['default']
  }
}
