// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AssetList: typeof import('./src/components/AssetList/index.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    Render: typeof import('./src/components/Render/index.vue')['default']
    RenderItem: typeof import('./src/components/Render/RenderItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingConfig: typeof import('./src/components/SettingConfig/index.vue')['default']
  }
}
